### ISSUE TITLE
Not working correct for grids

### ISSUE THREAD

**Issue by thomaspp** [vaadin4qbanos/vaadin-jsclipboard-addon#12]
Hello!

Great add-on, but unfortunately it does not work correct within a grid. Only the viewable rows are copied, not the complete content. Is there a chance to fix this?

Regards,
Thomas

**Comment by rubenqba** [comment]
I think when an element is hidden, Vaadin does not send it to the presentation layer. I suppose that for that reason the extension can not copy data that does not exist.

**Comment by thomaspp** [comment]
Okay.. So it seems there is no chance to copy all the data... ;-(

**Comment by gbuompastore** [comment]
Please give a solution for use ClipboardButton in a Grid with a TextArea (rendered with a ComponentRenderer)
https://vaadin.com/directory#!addon/componentrenderer

When i click on the button nothing event is fired

**Comment by rubenqba** [comment]
Fixed in new release
