### ISSUE TITLE
Could not find artifact vaadin-jsclipboard-root

### ISSUE THREAD

**Issue by dyorgio** [vaadin4qbanos/vaadin-jsclipboard-addon#15]
Could not find artifact com.github.vaadin4qbanos:vaadin-jsclipboard-root:pom:1.0.5 in vaadin-addons (http://maven.vaadin.com/vaadin-addons)

**Comment by rubenqba** [comment]
Hi, thanks for letting me know and I apologize for not having noticed it in time. Already a person who contacted me, verified that the Addon can now be successfully downloaded.
Sorry again for the delay.

**Comment by dyorgio** [comment]
Same problem on 1.0.6 version.
