### ISSUE TITLE
Latest release 1.0.9 doesn't include JSClipboard

### ISSUE THREAD

**Issue by corneil** [vaadin4qbanos/vaadin-jsclipboard-addon#22]
I have added the dependency:
```
<dependency>
  <groupId>com.github.vaadin4qbanos</groupId>
  <artifactId>jsclipboard</artifactId>
  <version>1.0.9</version>
</dependency>
```
to my project but the jar doesn't include JSClipboard only `com.vaadin.jsclipboard.ClipboardButton` and yet it seems that class has been part of the project for a few years.
Is this the correct version? Am I missing something?

**Comment by rubenqba** [comment]
I think you maybe miss something. It does not make sense that you can see one class and not the other ```com.vaadin.jsclipboard.JSClipboard```.
However, we are preparing a new release, probably by the end of the week. Maybe you want to consider waiting a few days for this new version.

**Comment by rubenqba** [comment]
Hi @corneil could you check the new version released?
