### ISSUE TITLE
The addon does not work in Vaadin 7.3.x

### ISSUE THREAD

**Issue by johannest** [vaadin4qbanos/vaadin-jsclipboard-addon#9]
I made Vaadin 7.3.x compatible version here: https://github.com/johannest/vaadin-jsclipboard-addon 

I'll make a pull request for that too

**Comment by ghernandezr** [comment]
hello, can you make a pull request?

**Comment by ghernandezr** [comment]
thanks for the pull request. It will be released in the next version

**Comment by johannest** [comment]
Thank you very much! You probably already know that my changes won't work with Vaadin 7.4+ (since they use different json libraries). So you need to have to have two separate releases: one for Vaadin 7.3 and one for 7.4+

**Comment by ghernandezr** [comment]
Thanks, you're right
